# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "EET"
  end
  config.vm.box = "alpine/alpine64"
  config.vm.network "private_network", ip: "192.168.10.14"
  config.vm.synced_folder ".", "/mnt/host_machine"
  config.vm.provider :virtualbox do |vb|
      vb.name = "alpine-tst-0.1"
      vb.memory = "512"
  end
  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
  end
end
