version: '3.1'

services:

  galera1:
    image: mariadb:10.4
    container_name: galera1
    restart: always
    ports:
      - 3306
      - 4444
      - 4567
      - 4568
    volumes: 
      - .galera1/cnf/galera1.cnf:/etc/my.cnf.d/galera.cnf
    environment:
      - MYSQL_ROOT_PASSWORD: ASdf456+
      - DISCOVERY_SERVICE: galera1:2379, galera2:2379, galera3:2379
      - CLUSTER_NAME: my_galera_cluster

  galera2:
    image: mariadb:10.4
    container_name: galera2
    restart: always
    ports:
      - 3306
      - 4444
      - 4567
      - 4568
    volumes: 
      - .galera2/cnf/galera2.cnf:/etc/my.cnf.d/galera.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ASdf456+

  galera3:
    image: mariadb:10.4
    container_name: galera3
    restart: always
    ports:
      - 3306
      - 4444
      - 4567
      - 4568
    volumes: 
      - .galera3/cnf/galera3.cnf:/etc/my.cnf.d/galera.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ASdf456+

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080