# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "EET"
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.8.2"
  config.vm.synced_folder ".", "/mnt/host_machine"
  config.vm.provider :virtualbox do |vb|
      vb.name = "minikube_ubuntu"
      vb.memory = "4096"
      vb.cpus = "2"
  end
  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
  end
end
