node1:
    image: mariadb:10.4
    hostname: node1
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - REPLICATION_PASSWORD=test
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=test
      - GALERA=On
      - NODE_NAME=node1
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://
    command: --wsrep-new-cluster

node2:
    image: mariadb:10.4
    hostname: node2
    links:
      - node1
    ports:
      - 23306:3306
    environment:
      - REPLICATION_PASSWORD=test
      - GALERA=On
      - NODE_NAME=node2
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://node1
      
node3:
    image: mariadb:10.4
    hostname: node3
    links:
      - node1
    ports:
      - 33306:3306
    environment:
      - REPLICATION_PASSWORD=test
      - GALERA=On
      - NODE_NAME=node3
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://node1


adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080      
