version: '2'

services:
  mariadb-galera:
    image: bitnami/mariadb-galera:10.4-centos-7
    ports:
      - '3306:3306'
      - '4444:4444'
      - '4567:4567'
      - '4568:4568'
    volumes:
      - 'mariadb_galera_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  mariadb_galera_data:
    driver: local
